# Generated by Django 5.1.4 on 2025-03-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0013_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(editable=False, max_length=70),
        ),
    ]
