# Generated by Django 5.1.4 on 2025-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0018_alter_article_author_alter_article_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=70, unique_for_year='pub_date'),
        ),
    ]
