# Generated by Django 5.1.4 on 2025-03-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0019_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
