# Generated by Django 5.1.4 on 2025-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0020_category_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='post_app.category'),
        ),
    ]
